- name: Build kernel
        run: |
          export ARCH=arm64
          export KBUILD_BUILD_USER="Sbase25"
          export KBUILD_BUILD_HOST="GitHub-Actions"
          export PATH="$GITHUB_WORKSPACE/toolchains/clang/bin:$PATH"
          
          # Added KCFLAGS to bypass the bfq-iosched.c argument error
          MAKE_ARGS="ARCH=arm64 \
            O=out \
            CC=clang \
            CROSS_COMPILE=aarch64-linux-gnu- \
            CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
            LLVM=1 \
            LLVM_IAS=1 \
            KCFLAGS=-Wno-implicit-function-declaration -Wno-argument-mismatch"

          mkdir -p out

          # Identify Base Config
          if [ -f "arch/arm64/configs/vendor/lito-perf_defconfig" ]; then
              BASE_CONF="vendor/lito-perf_defconfig"
          else
              BASE_CONF="vendor/lito_defconfig"
          fi

          # 1. Generate config
          make $MAKE_ARGS $BASE_CONF

          # 2. Merge Samsung Fragment
          if [ -f "arch/arm64/configs/vendor/samsung/a52xq.config" ]; then
              cat arch/arm64/configs/vendor/samsung/a52xq.config >> out/.config
              make $MAKE_ARGS olddefconfig
          fi

          # 3. Compile
          make -j$(nproc --all) $MAKE_ARGS
